server:
  port: 8083

#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ERA_Commerce
#    username: root
#    password: Reinamimi
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ERA_Commerce
    username: root
    password: emma12345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


orderService:
  orderUrl: http://localhost:8082/orders

userService:
  userUrl: http://localhost:8081