server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ERA_Commerce
    username: root
    password: emma12345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true